# Generated by Django 4.2.7 on 2023-11-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_company_company_name_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='inactive', max_length=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
