# Generated by Django 4.2.7 on 2023-11-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='description',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=8),
        ),
    ]
