# Generated by Django 4.2.7 on 2023-11-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0008_remove_jobpost_location_jobpost_city_jobpost_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
    ]
