# Generated by Django 4.2.7 on 2023-11-25 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
