# Generated by Django 4.2.7 on 2023-11-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_delete_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sector",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Categoría"
            ),
        ),
    ]
