# Generated by Django 4.2.7 on 2023-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_company_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="cantidad_empleados",
            field=models.CharField(
                choices=[
                    ("1-10", "Entre 1 y 10"),
                    ("11-50", "Entre 11 y 50"),
                    ("51-150", "Entre 51 y 150"),
                    ("151-300", "Entre 151 y 300"),
                    ("301-500", "Entre 301 y 500"),
                    ("501-1000", "Entre 501 y 1000"),
                    ("1001-más", "Más de 1001"),
                ],
                default=-9,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="razón_social",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
