# Generated by Django 4.2.7 on 2023-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_company_cantidad_empleados_company_razón_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="cantidad_empleados",
            field=models.CharField(
                choices=[
                    ("1-10", "Entre 1 y 10"),
                    ("11-50", "Entre 11 y 50"),
                    ("51-150", "Entre 51 y 150"),
                    ("151-300", "Entre 151 y 300"),
                    ("301-500", "Entre 301 y 500"),
                    ("501-1000", "Entre 501 y 1000"),
                    ("1001-más", "Más de 1000"),
                ],
                max_length=50,
            ),
        ),
    ]
