# Generated by Django 4.2.7 on 2023-11-30 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobpost",
            old_name="type",
            new_name="sector",
        ),
    ]
