# Generated by Django 4.2.7 on 2023-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_rename_type_jobpost_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.CharField(
                choices=[("Full-time", "Full-time"), ("Part-time", "Part-time")],
                default="Full-time",
                max_length=20,
            ),
        ),
    ]
