# Generated by Django 4.2.7 on 2023-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("No Binario", "No Binario"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="category",
            field=models.CharField(
                choices=[("Full-time", "Full-time"), ("Part-time", "Part-time")],
                default="full-time",
                max_length=20,
            ),
        ),
    ]
