# Generated by Django 4.2.7 on 2023-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_userprofile_genero_alter_jobpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="document_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DNI", "DNI"),
                    ("CI", "CI"),
                    ("LE", "LE"),
                    ("LC", "LC"),
                    ("PASSPORT", "Pasaporte"),
                ],
                max_length=10,
            ),
        ),
    ]
