# Generated by Django 4.2.7 on 2023-12-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="cuit",
            field=models.CharField(default="", max_length=13),
            preserve_default=False,
        ),
    ]
