# Generated by Django 4.2.7 on 2023-12-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_company_cuit"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="application_limit",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
