# Generated by Django 4.2.7 on 2023-12-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_jobpost_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
