# Generated by Django 4.2.7 on 2023-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_alter_userprofile_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="cuit",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
