# Generated by Django 4.2.7 on 2023-12-07 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_jobpost_address_alter_company_cuit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="province",
            new_name="province_name",
        ),
        migrations.RenameField(
            model_name="jobpost",
            old_name="province",
            new_name="province_name",
        ),
    ]
