# Generated by Django 4.2.7 on 2023-12-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_rename_province_company_province_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="province_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
