# Generated by Django 4.2.7 on 2023-12-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0033_rename_answer_faq_content_rename_question_faq_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_answer", models.TextField()),
            ],
        ),
    ]
