# Generated by Django 4.2.7 on 2023-12-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="complete_answer",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
