# Generated by Django 4.2.7 on 2023-12-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_question_complete_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="comuni",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Comuni"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="provincia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Provincia"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="regioni",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Regioni"
            ),
        ),
    ]
