# Generated by Django 4.2.7 on 2023-12-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0036_company_comuni_company_provincia_company_regioni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="comuni",
        ),
        migrations.RemoveField(
            model_name="company",
            name="provincia",
        ),
        migrations.RemoveField(
            model_name="company",
            name="regioni",
        ),
        migrations.AddField(
            model_name="company",
            name="comuna_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Comuna (Italia)"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="provincia_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Provincia (Italia)"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="region_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Región (Italia)"
            ),
        ),
    ]
