# Generated by Django 4.2.7 on 2023-12-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0037_remove_company_comuni_remove_company_provincia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(
                choices=[("AR", "Argentina"), ("IT", "Italia")],
                default="AR",
                max_length=2,
            ),
        ),
    ]
