# Generated by Django 4.2.7 on 2023-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0038_company_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="comuna_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Comuna (Italia)"
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="provincia_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Provincia (Italia)"
            ),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="region_it",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Región (Italia)"
            ),
        ),
    ]
