# Generated by Django 4.2.7 on 2023-12-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0040_alter_company_phone_number_alter_jobpost_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuser",
            name="admin_code",
        ),
        migrations.AddField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
