# Generated by Django 4.2.7 on 2023-12-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0041_remove_adminuser_admin_code_adminuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
