# Generated by Django 4.2.7 on 2024-01-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0042_adminuser_email_confirmed_company_email_confirmed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogEntryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("it", "Italian")], max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "blog_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="accounts.blogentry",
                    ),
                ),
            ],
            options={
                "unique_together": {("blog_entry", "language")},
            },
        ),
    ]
