# Generated by Django 4.2.7 on 2024-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0043_blogentrytranslation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="content",
            new_name="content_es",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="title",
            new_name="title_es",
        ),
        migrations.AddField(
            model_name="faq",
            name="content_it",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faq",
            name="title_it",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
