# Generated by Django 4.2.7 on 2024-01-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0044_rename_content_faq_content_es_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="content_es",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="title_es",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="content_it",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="title_it",
        ),
        migrations.CreateModel(
            name="FAQTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Español"), ("it", "Italiano")], max_length=2
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="accounts.faq",
                    ),
                ),
            ],
            options={
                "unique_together": {("faq", "language")},
            },
        ),
    ]
